[package]
name = "okto"
version = "1.0.0"
authors = ["CallidusU <callidusumbra@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A Discord bot for getting information about upcoming rocket launches"


[dependencies]
serenity = "0.8"
lazy_static = "1.4"
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
chrono = "0.4.13"
rand = "0.7"
bson = "1.1.0"
url = "2.1"
regex = "1"
num_cpus = "1.13"
threadpool = "1.8"

[dependencies.mongodb]
version = "1.1.1"
default-features = false
features = ["sync"]
