[package]
name = "okto"
version = "0.1.0"
authors = ["CallidusU <callidusumbra@gmail.com>"]
edition = "2018"


[dependencies]
serenity = "0.8"
lazy_static = "1.4"
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
chrono = "0.4.13"
rand = "0.7"
bson = "1.0.0"
url = "2.1"

[dependencies.mongodb]
version = "1.0.0"
default-features = false
features = ["sync"]
